apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    pod-security.kubernetes.io/enforce: {{ .Values.namespaceLabels.podSecurityEnforce | default "restricted" }}
    {{- include "webhooklite.labels" . | nindent 4 }}