{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default "webhook-certs" }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "webhooklite.labels" . | nindent 4 }}
type: {{ .Values.secret.type | default "kubernetes.io/tls" }}
{{- if .Values.secret.tls.crt }}
data:
  tls.crt: {{ .Values.secret.tls.crt }}
  tls.key: {{ .Values.secret.tls.key }}
{{- else }}
# Certificates --set-file
# Tip:
# helm upgrade --install webhooklite ./helm/webhooklite \
#   --set-file secret.tls.crt=./certs/tls.crt \
#   --set-file secret.tls.key=./certs/tls.key
{{- end }}
{{- end }}