apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: webhooklite-validation
webhooks:
  - name: validate.webhooklite.local
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
    clientConfig:
      service:
        name: webhooklite
        namespace: default
        path: "/validate"
        port: 8443
      caBundle: " LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlESHpDQ0FnZWdBd0lCQWdJVUdLYXJZa1R4eUJGRmE4VElFd29Ya1JCTFFWc3dEUVlKS29aSWh2Y05BUUVMDQpCUUF3SWpFZ01CNEdBMVVFQXd3WGQyVmlhRzl2YTJ4cGRHVXVaR1ZtWVhWc2RDNXpkbU13SGhjTk1qWXdOekkxDQpNakEwT0RVMFdoY05Nell3TnpJeU1qQTBPRFUwV2pBaU1TQXdIZ1lEVlFRRERCZDNaV0pvYjI5cmJHbDBaUzVrDQpaV1poZFd4MExuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOV1RGQ0lZDQpIY2pWVXc5bG5xVGpWVmFURFdOUDBUR3BXT09BdGxScEc3Q2tnMlpVUVMwN1RwSDJFZHpGU09nS3oyajVBSUMvDQo4QnJEL3FuV2VVeVRNZlBXWlV3NTE1NkpIRUpiV1BjdndPUGJXczBBQUdESER3YVBTRUVPc25ud01vQ0cwYXJoDQpTL2p6aG02Ri9zdGlaMG9Relo4UGozR01zUHB0NG0vQU9OOThtYU51dFR6TXk2VUdhM2ZkVzlZNUJOVElsM1Y5DQpOSzVYWFcxQ0ZUTUQ5WGVrUXFZbkpyVTVYckx2RXk5VXBOaXc0VWFudG1JWFJ1REROOSttT0xZLzJyMVYzSjhhDQpGNWpIbEwzWWd3UDR2L2hjaXRNSDlIRTJrMmVTMVVBOWhXTWdsOWxYMTVhbjRQMWZyckU2ZHFMMjNnZEV0RzAwDQpQMURicXRGNXQ4V2V6aDhDQXdFQUFhTk5NRXN3U1FZRFZSMFJCRUl3UUlJWGQyVmlhRzl2YTJ4cGRHVXVaR1ZtDQpZWFZzZEM1emRtT0NKWGRsWW1odmIydHNhWFJsTG1SbFptRjFiSFF1YzNaakxtTnNkWE4wWlhJdWJHOWpZV3d3DQpEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBTW4ySHQ3WndPUUhqSXoyWGdFTkY1TmtsYjFWb0ZpZUFCWXF3Mk1JDQpORnpGd2kzcFU4c21LL3JjOXJ3UkJ0YkR3SUFXREtrQjY5WmFMMzluVXFJVURCR1U4eXFYcmt5K2d2UjUweVNrDQo2VDBqVkZISEtLUjJOallmaTJLSGEzZE4zNFR2Y2RwMXRjUXowcnRDbVBPR1VUemcvRllQODhudFlja0ZyUy9UDQo3ZzFQbEd3aEtiaFRuQVV4YW9sT3NNb0p6ckd5TWJOMXhmNjBIYzMwRFROeVRKWTMwemM1K2ROV1d2NFNFVDRyDQpPNnZoZEFqOURudTRCV2psT3RtSFpPbXdoQi94Q2JQTWl3T3RXRmsxZWZOMWd0d2xXcExzVUo2a2hNTG9XYVhGDQpjMmtYbXc0VUVuemRhVEsrQkVsTnNTSHFha2pGa3kwQldxNXZiWHlMUSswVURNaz0NCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0NCg=="
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5