apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: webhooklite-validation
webhooks:
  - name: validate.webhooklite.local
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["argocd", "webhook-system", "kube-system", "kube-public", "kube-node-lease"]
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
    clientConfig:
      service:
        name: webhooklite
        namespace: webhook-system
        path: "/validate"
        port: 443
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlET3pDQ0FpT2dBd0lCQWdJVVJkTUJxZnB1SU00a2ZJNmIxU2c2ZWJiMFhWWXdEUVlKS29aSWh2Y05BUUVMDQpCUUF3S1RFbk1DVUdBMVVFQXd3ZWQyVmlhRzl2YTJ4cGRHVXVkMlZpYUc5dmF5MXplWE4wWlcwdWMzWmpNQjRYDQpEVEkyTURrd05qRTJOREEwTVZvWERUTTJNRGt3TXpFMk5EQTBNVm93S1RFbk1DVUdBMVVFQXd3ZWQyVmlhRzl2DQphMnhwZEdVdWQyVmlhRzl2YXkxemVYTjBaVzB1YzNaak1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBDQpNSUlCQ2dLQ0FRRUFueS85UmZMOTJDL0padDNzTUZmSEtodEErNFBPUnFmKytHTHIydXFNOEo0bE1SU2c0dlV0DQpWL0M5dFp5d25ETjRHUTBJR2pxMVFjWk96ZW0zUXlUeVJ3OUFramJRelBJV0IvSEZhTDgrV0J1b0tkcEFsNG52DQp6dVRRSk53dTNzZnA4UlI5TDVhZTFjNldXcDEvMktTQnd2L3kyRmZlY0wwcThGZERpQTQyeWNuWS9ZTlJGT1E0DQpmVVMrWnhKK3V1VkNPV2RYR1gzRS9yZ1BSZllWZEZxS0lONHhDYkVuWWxnRmZRekh2RjlZZHFUU1RXZkdWWVgrDQprdWQ1bFlmSlpoMmkrYTJ5eGszenJiTGYxR0tYSC9RTnhjVjV2YnJ4dUkzK0VhQ01JY3pBNXBRYmlhZElnOXgwDQpKbDM5Q0x3RW5EWVRRbEREL1l1Wkg5TGJEY05vYW1OSURRSURBUUFCbzFzd1dUQlhCZ05WSFJFRVVEQk9naDUzDQpaV0pvYjI5cmJHbDBaUzUzWldKb2IyOXJMWE41YzNSbGJTNXpkbU9DTEhkbFltaHZiMnRzYVhSbExuZGxZbWh2DQpiMnN0YzNsemRHVnRMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUI5DQplOXlIZGZiaUdBWWhhMTdCeDM4dlVYTnhUZXhCZDE1Q0lDMUFYdlIyNWltZzZ6VGFmSi9sS2N2Wmp2V2ZRc1NLDQpVVUFiQmUxV2QrTjZyUGFEa0VxVHNLTmYwOUxuS1ZEdEh1TVlqbDVrYXREOVBSRU0wMnpTZGx4ZTRwOW5mMmJKDQpORnJRRzBZN1BpUE9hSU1ieWdPcW82ZmNaWTFGOTMvcVNTMGRlVkE2VTcvWmVMSHN2Uy9XbkdoWHJyNWVsYlU3DQpqK3BuWmRSY2pMNzlYNXU2endhSkVJanVieXF6eXdSUW9OK283UE9pcnJGUHd2dHB3YTBtV3lDVG5jb3hndlVaDQpOdTRwREFpQUo1ekFNcTNqanhGQ0QvQmxKYlFWMnpLN2Jkclh2dnpTRDdqMm5COE93MC92b1RTUC9rQzA4NkY5DQpIWE54b0lOL0Z2RTB2bEJRUDhCbg0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0K"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5