apiVersion: v1
kind: Pod
metadata:
  name: good-pod
spec:
  containers:
    - name: good-pod
      image: nginxinc/nginx-unprivileged:1.26-alpine
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"